Revert "Switch jest config to full TS version"
Jest will not transpile a .TS config file which lives within node_modules.

SyntaxError: Cannot use import statement outside a module

This reverts commit ef0114fd9855886cbee8a9a2fd8fe9b3488e6a7f.