Revert "Do not include the tsconfig.json file in the bundle"
Without the tsconfig.json file the .ts scripts will not work and always throw:

SyntaxError: Cannot use import statement outside a module

This reverts commit 9ac0eb3c4bda71d8ee7aa28cce71681ed8e10963.